# Generated by Django 3.2 on 2021-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('screenshot', models.ImageField(blank=True, upload_to='')),
                ('language', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('live_url', models.URLField(blank=True)),
                ('video_demo_url', models.URLField()),
                ('github_url', models.URLField(blank=True)),
            ],
        ),
    ]
