# Generated by Django 3.2 on 2021-04-13 20:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210413_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
